// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// qscore
double qscore(NumericVector y, NumericVector x, NumericVector T, IntegerVector cl, int ncl);
RcppExport SEXP _crctStepdown_qscore(SEXP ySEXP, SEXP xSEXP, SEXP TSEXP, SEXP clSEXP, SEXP nclSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cl(clSEXP);
    Rcpp::traits::input_parameter< int >::type ncl(nclSEXP);
    rcpp_result_gen = Rcpp::wrap(qscore(y, x, T, cl, ncl));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_crctStepdown_qscore", (DL_FUNC) &_crctStepdown_qscore, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_crctStepdown(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
