# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qscore <- function(y, x, Tr, cl, ncl) {
    .Call(`_crctStepdown_qscore`, y, x, Tr, cl, ncl)
}

qscorew <- function(y, x, Tr, g, sigma, cl, ncl) {
    .Call(`_crctStepdown_qscorew`, y, x, Tr, g, sigma, cl, ncl)
}

